apiVersion: v1
kind: Secret
metadata:
  name: vayusutra-secrets
  namespace: vayusutra-system
type: Opaque
stringData:
  AUTH_SECRET_KEY: "VAYUSUTRA-APIX-SECRET-KEY-SIH26056-MOSPI-RBI-DGCA-2026-PRODUCTION"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vayusutra-data-pvc
  namespace: vayusutra-system
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
